import pygame as pg
box=pg.image.load("Sprites/08-box/idle.png")
player=pg.image.load("Sprites/01-King Human/Ground (78x58).png")
plgo=pg.image.load("Sprites/01-King Human/Run (78x58).png")
terrain=pg.image.load("Sprites/14-TileSets/Terrain (32x32).png")
jump=pg.image.load("Sprites/01-King Human/Jump (78x58).png")
idle=pg.image.load("Sprites/01-King Human/Idle (78x58).png")
decoration=pg.image.load("Sprites/14-TileSets/Decorations (32x32).png")
plgo=pg.transform.scale(plgo,(plgo.get_width()*2,plgo.get_height()*2))
player=pg.transform.scale(player,(player.get_width()*2,player.get_height()*2))
box=pg.transform.scale(box,(box.get_width()*2,box.get_height()*2))
terrain=pg.transform.scale(terrain,(terrain.get_width()*2,terrain.get_height()*2))
jump=pg.transform.scale(jump,(jump.get_width()*2,jump.get_height()*2))
idle=pg.transform.scale(idle,(idle.get_width()*2,idle.get_height()*2))
decoration=pg.transform.scale(decoration,(decoration.get_width()*2,decoration.get_height()*2))
